version: '3.4'
services:
    back-youtube:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        container_name: back-youtube
        image: back-youtube
        network_mode: bridge